### ISSUE TITLE
KL divergence for tagging? 

### ISSUE THREAD

**Issue by spookyQubit** [yhy1117/X-Mixup#1]
Hi @yhy1117 , first of all, great work and thanks a lot for making the code public.

I had a quick question regarding the consistency loss (Equation 7 in https://openreview.net/pdf?id=OjPmfr9GkVv). For tagging tasks (such as NER/POS), is the KL divergence part of the loss used? For sentence level tasks (such as XNLI), I think I understand how KL divergence could be used. But for tagging tasks, it is not exactly clear to me. 

Would really appreciate any pointers which would help me understand this better. 

Thanks.

**Comment by yhy1117** [comment]
Hi, thanks for your interest in our work :)
For tagging and QA tasks, we only use the representation consistency loss (MSE loss), without the prediction consistency loss (KL loss). KL loss only exists in the classification task.
You can refer to detailed explanation under the Equation 8.

**Comment by spookyQubit** [comment]
Thanks a lot @yhy1117. That makes sense. 
(Closing this issue. If I have further questions, I will reach out.)
Again, thanks a lot for the quick reply.
